version: '3.8'
services:

  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    environment:
      - QUART_APP=app.py
      - QUART_ENV=development
    ports:
      - "${SCRAPER_PORT}:8080"
    networks:
      - backend

networks:
  backend:
    external:
      name: flaskapp
